//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATP2_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Sales_Id { get; set; }
        public int Info_Id { get; set; }
        public string Invoice_Number { get; set; }
        public System.DateTime Date { get; set; }
        public int Product_Id { get; set; }
        public int Quantity { get; set; }
        public double Total_Price { get; set; }
        public double Unit_Price { get; set; }
        public int Catagory_Id { get; set; }
    
        public virtual Catagory Catagory { get; set; }
        public virtual Information Information { get; set; }
        public virtual Product Product { get; set; }
    }
}
