//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATP2_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int id { get; set; }
        public int Product_Id { get; set; }
        public int Catagory_Id { get; set; }
        public int Quantity { get; set; }
    
        public virtual Catagory Catagory { get; set; }
        public virtual Product Product { get; set; }
    }
}
